### ISSUE TITLE
Pull request tests run twice?

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/meta#145]
I have the impression that the tests after a PR push are run twice, once with label `(push)` and once with label (`pull_request`). If this impression is correct, what is the motivation?

If there is no strong reason, we should avoid test duplication, as this would reduce testing time.

**Comment by dataflake** [comment]
The impression is correct, the GitHub Actions for those tests are triggered on both pushes and pull request pushes.

I think it's set up that way to avoid situations where no tests are run at all, like someone creates a PR from a fork. In that case the forked branch (and tests that may or may not run on it, depending on the forkin side's setup) is not readily visible to a reviewer.

A quick glance at the GH Actions docs didn't show an obvious way to say "if two triggers want to execute the tests just skip one of them".

**Comment by dataflake** [comment]
I found an article that describes how to write a condition that basically says "run on push and run on PR if the PR is from a forked repository", see https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/:

```
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != "pull_request" || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
```

**Comment by mauritsvanrees** [comment]
I have lately done it [like this](https://github.com/plone/plone.namedfile/blob/master/.github/workflows/tests.yml):

```
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
```

In the branches you would list `master` or `main` plus any maintenance branches.
