### ISSUE TITLE
A better way to specify a Python prerelease version

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#238]
Right now the value of ``FUTURE_PYTHON_VERSION`` in ``shared/packages.py`` is set as a range, currently ``3.13.0-alpha - 3.13.0``. That's a bit clunky because that version string is inserted in many places.

The documentation for the ``setup-python`` GH action mentions a cleaner way that uses the flag ``allow-prereleases: true``, so you could define ``FUTURE_PYTHON_VERSION`` as a "clean" ``3.13`` and write it all like this:

```
- uses: actions/setup-python@v4
  with:
    python-version: "3.13"
    allow-prereleases: true
```

See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases.
