### ISSUE TITLE
Add more pre-commit hooks

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#284]
The following hooks got deleted from this repo in #282.

```yaml
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: debug-statements
            language_version: python3
# If needed:
    - repo: local
      hooks:
          - id: rst
            name: rst
            entry: rst-lint --encoding utf-8
            exclude: ./doc/.*
            files: .rst
            language: python
            additional_dependencies: [pygments, restructuredtext_lint]
# This can deal with sphinx directives
    - repo: https://github.com/myint/rstcheck
      rev: "v6.2.4"
      hooks:
      - id: rstcheck
        args: [--ignore-messages, Duplicate implicit target.*]
```

Task: Find out what is helpful for all repos and add them back.
